### PR TITLE
upgraded versions to align with JBEAP 7.0.0

### PR DESCRIPTION
**Pull request by mbiarnes**
upgrades the versions
ch.qos.cal10n
commons-codec
com.fasterxml.jackson
com.google.guava
com.h2database
com.mchange.c3p0

### CODE REVIEW

**Comment by psiroky** [comment]
+1

**Comment by hchiorean** [comment]
+1

**Comment by cunningt** [comment]
+1

**Comment by psiroky** [comment]
Merged as part of https://github.com/jboss-integration/jboss-integration-platform-bom/commit/f5ac8e34052f5d640327515242f41dd2c4dd08ad.

**Pull request closed without merging**
