### PR TITLE
upgraded version.org.eclipse.jgit to align with kie-platform.bom

### PR DESCRIPTION
**Pull request by mbiarnes**

### CODE REVIEW

**Comment by hchiorean** [comment]
+1

**Comment by psiroky** [comment]
+1

**Comment by objectiser** [comment]
+1

**Comment by cunningt** [comment]
+1

**Comment by psiroky** [comment]
Merged into master as https://github.com/jboss-integration/jboss-integration-platform-bom/commit/a50ae33e4e259931aefab76b946bdff9ea2bf46f

**Pull request closed without merging**
