### PR TITLE
Added jboss-product profile for usage with the versions plugin

### PR DESCRIPTION
**Pull request by wolfc**
You should just try it:
$ mvn -Pjboss-product versions:compare-dependencies -DremotePom=org.jboss.as:jboss-as-parent:7.4.2.Final-redhat-2
Or:
$ mvn versions:compare-dependencies -DremotePom=org.wildfly:wildfly-parent:9.0.0.Alpha2-SNAPSHOT
But that doesn't take into account some GAV renames. ;-)

### CODE REVIEW

**Comment by cunningt** [comment]
+1

**Comment by objectiser** [comment]
+1

**Comment by hchiorean** [comment]
+1

**Comment by mareknovotny** [comment]
This is really old PR we don't need anymore

**Pull request closed without merging**
