### PR TITLE
10th upgrade of version to align with JBEAP 7.0.0

### PR DESCRIPTION
**Pull request by mbiarnes**
updated versions:
org.jboss.spec.javax.servlet.jstl.jboss-jstl-api_1.2_spec
org.jboss.staxmapper
org.jboss.weld.weld-api
org.jboss.ws.api
org.jboss.ws.spi
org.jboss.ws.cxf

### CODE REVIEW

**Comment by psiroky** [comment]
I've upgraded weld as part of https://github.com/jboss-integration/jboss-integration-platform-bom/pull/301

**Comment by hchiorean** [comment]
+1

**Comment by psiroky** [comment]
+1, I will deal with the conflicts (with https://github.com/jboss-integration/jboss-integration-platform-bom/pull/301) when merging.

**Comment by cunningt** [comment]
+1

**Comment by psiroky** [comment]
Merged by https://github.com/jboss-integration/jboss-integration-platform-bom/commit/8a28c24860fdcecfe51f646866886a67021f71f6

**Pull request closed without merging**
