### PR TITLE
upgrade org.apache.maven

### PR DESCRIPTION
**Pull request by mbiarnes**
alignment to EAP 6.4

### CODE REVIEW

**Comment by ge0ffrey** [comment]
+1

**Comment by hchiorean** [comment]
+1

**Comment by objectiser** [comment]
+1

**Comment by psiroky** [comment]
Just a heads up. The Aether library (dependency of maven) was "converted" from Sonatype to Eclipse between the versions `3.0.5` and `3.2.1`. Among others, the groupId changed from `org.sonatype.aether` to `org.eclipse.aether`.

This has caused some issues for us in past as different libraries (e.g. kie-ci and shrinkwrap-maven-resolver) depend on different versions and they get mixed, mainly because the groupId has been changed.

I still agree that we should upgrade, just wanted to make others aware of potential issues.

**Pull request merged**
