### PR TITLE
[UF-415]: Update xml-apis version to 1.4.01

### PR DESCRIPTION
**Pull request by tomasdavidorg**
This fixes the problem with compilation of UF Tasks Project.

### CODE REVIEW

**Comment by psiroky** [comment]
The `xml-apis-ext` does not exist in the version 1.4.01. I am not sure though if we are using it somewhere. We will either need to remove it completely or use the older version.

**Comment by tomasdavidorg** [comment]
I split off `xml-apis-ext` version from `xml-apis` version.

**Comment by psiroky** [comment]
+1

**Comment by cunningt** [comment]
+1

**Comment by hchiorean** [comment]
+1

**Pull request merged**
