### PR TITLE
SWITCHYARD-2855 Add camel-dozer support with endpoint/data format def…

### PR DESCRIPTION
**Pull request by igarashitm**
…inition enabled

Added camel-dozer and camel-jackson

### CODE REVIEW

**Comment by igarashitm** [comment]
oops, am I missing something? ${version.org.apache.camel} is specified for those version though.

**Comment by psiroky** [comment]
@igarashitm this is an issue with the test. I am looking into that now.

**Comment by psiroky** [comment]
@igarashitm test fixed and the build is green!

**Comment by psiroky** [comment]
+1

**Comment by igarashitm** [comment]
@psiroky cool, thanks for the quick fix!

**Comment by hchiorean** [comment]
+1

**Comment by cunningt** [comment]
+1

**Pull request merged**
