### PR TITLE
6th upgrade of versions to align with JBEAP 7.0.0

### PR DESCRIPTION
**Pull request by mbiarnes**
upgraded verision
org.codehaus.woodstox
org.hornetq
org.infinispan

### CODE REVIEW

**Comment by hchiorean** [comment]
+1

**Comment by cunningt** [comment]
+1

**Comment by psiroky** [comment]
It seems the following artifacts are no longer being released as part of Infinispan: `org.infinispan:infinispan-cachestore-bdbje:jar:8.1.2.Final, org.infinispan:infinispan-cachestore-jdbm:jar:8.1.2.Final`

We need to replace them with alternatives (if there are some), or remove them completely.

**Comment by hchiorean** [comment]
+1 for removing them; ModeShape no longer requires them

**Comment by mbiarnes** [comment]
I removed both dependencies from jboss-integration-platform-bom

**Comment by psiroky** [comment]
Merged as part of https://github.com/jboss-integration/jboss-integration-platform-bom/commit/f5ac8e34052f5d640327515242f41dd2c4dd08ad.

**Pull request closed without merging**
