### PR TITLE
upgrade org.jboss.as

### PR DESCRIPTION
**Pull request by mbiarnes**
alignment to EAP 6.4

### CODE REVIEW

**Comment by hchiorean** [comment]
+1

**Comment by ge0ffrey** [comment]
+1 Presuming that that version actually exists on jboss nexus, of course :)

**Comment by psiroky** [comment]
I think the version should be `7.5.0.Final-redhat-15` as that is the version available in JBoss Nexus.

**Comment by objectiser** [comment]
+1 once the specific version has been clarified.

**Comment by mbiarnes** [comment]
the available version of org.jboss.as is `7.5.0.Final-redhat-15`  there is no 
version `7.5.0.Final` on Nexus

**Comment by mbiarnes** [comment]
this pull request will be closed and another opened that upgrades to `7.5.0.Final-redhat-15`

**Pull request closed without merging**
