### PR TITLE
upgrade jboss-jsp-api_2.2_spec

### PR DESCRIPTION
**Pull request by mbiarnes**
alignment to EAP 6.4

### CODE REVIEW

**Comment by objectiser** [comment]
+1

**Comment by ge0ffrey** [comment]
+1
      
        
        
      
      On 26-01-15 12:15, mbiarnes wrote:
    
    
      alignment to EAP 6.4
      
      You can view, comment on, or merge this pull request online
        at:
        https://github.com/jboss-integration/jboss-integration-platform-bom/pull/158
      Commit Summary
      
        upgrade jboss-jsp-api_2.2_spec
      
      File Changes
      
         M pom.xml
          (2) 
      
      Patch Links:
      
        https://github.com/jboss-integration/jboss-integration-platform-bom/pull/158.patch
        https://github.com/jboss-integration/jboss-integration-platform-bom/pull/158.diff
      
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by hchiorean** [comment]
+1

**Comment by cunningt** [comment]
+1

**Pull request merged**
