### PR TITLE
add resteasy-client

### PR DESCRIPTION
**Pull request by brmeyer**

### CODE REVIEW

**Comment by psiroky** [comment]
+1

**Comment by hchiorean** [comment]
+1

**Comment by objectiser** [comment]
+1

**Comment by cunningt** [comment]
+1

**Comment by psiroky** [comment]
I had to remove the `resteasy-client` artifact as it does not exist in version 2.x. See https://github.com/jboss-integration/jboss-integration-platform-bom/commit/00b31256c89ac22b0882bc9e4c1ee99b42154a90.

Please do check if the artifact exists when submitting PRs.

**Pull request merged**
