### PR TITLE
Upgrade Camel from 2.15.2 to 2.16.2.

### PR DESCRIPTION
**Pull request by cunningt**
Upgrade the version of Camel from 2.15.2 to 2.16.2 on the 6.0.x branch.

### CODE REVIEW

**Comment by psiroky** [comment]
@cunningt I presume this version is used by the next version of Fuse?

**Comment by cunningt** [comment]
@psiroky Fuse may bump again to 2.17, but this is the version we're currently working with.

**Comment by psiroky** [comment]
@cunningt ok, thanks for info.

+1

**Comment by hchiorean** [comment]
+1

**Pull request merged**
