### PR TITLE
Adding webservices (based on jbossws/cxf) dependencies, based on EAP 6.4

### PR DESCRIPTION
**Pull request by mrietveld**
These deps are taken from: 

http://<internal-repo>/latest/maven/org/jboss/as/jboss-as-parent/7.5.0.Final-redhat-17/jboss-as-parent-7.5.0.Final-redhat-17.pom (EAP 6.4) 
http://anonsvn.jboss.org/repos/jbossws/stack/cxf/tags/jbossws-cxf-4.3.4.Final/pom.xml (EAP 6.4 jbossws version)

bXms 6.1 will be based on EAP 6.4, and AFAICT, 6.4 is based on the 7.5.0.x build of jboss-as.

### CODE REVIEW

**Comment by hchiorean** [comment]
I thought we shouldn't have exclusions in the BOM, unless they are fixing a known issue. Are all those exclusions something we want in this case ?

**Comment by mrietveld** [comment]
There was recently (early december) a discussion on the jboss-integration-platform-developers list in which the general consensus was that exclusions were fine in the ip-bom. ("Exclusions in the ip-bom?" thread, starting 12-12-2014)

In this case, cxf brings in a couple things we don't want, most importantly:  
- spring
- geronimo spec jars (we already have our own and are using them)

The added exclusions are also exactly the same as what jboss webservices uses.

**Comment by hchiorean** [comment]
ok, in this case +1

**Comment by objectiser** [comment]
+1

**Comment by ge0ffrey** [comment]
+1

**Comment by ge0ffrey** [comment]
@kcbabo Are you ok with this PR?

**Comment by kcbabo** [comment]
Need @rcernich to chime in here as last time I checked SY 2.0 was targeted at EAP 6.3.

**Comment by rcernich** [comment]
SwitchYard needs an updated ip-bom which does not include any updates related to EAP 6.4.  Once there's a new version of ip-bom which includes https://github.com/jboss-integration/jboss-integration-platform-bom/pull/144, I'm OK with pushing this (i.e. after CR23).

**Comment by mrietveld** [comment]
@mbiarnes #144 has been merged: could you merge this as well?

**Comment by mrietveld** [comment]
oh, need to add one more cxf jar, just a sec.

**Comment by ge0ffrey** [comment]
CR23 is out a while already, so I presume rcernich's comment is a +1, so I am merging.

**Pull request merged**
