### PR TITLE
Prepare for EAP 6.4

### PR DESCRIPTION
**Pull request by wolfc**
Do not merge yet, this is a work in progress.

### CODE REVIEW

**Comment by pgier** [comment]
My understanding of the current problem and one of the reasons why carlo submitted the PR is that a lot of integration work is left up to the productization team when components are upgraded.  When a component upgrade comes in which has dependencies which conflicts with other components, how is this determined and who is currently responsible for fixing this?  Ideally, each component upgrade would be tested by at least a build, and preferably an integration testsuite, before the upgrade is merged.  If there are build/test failures, then it should be up to the person who submitted the upgrade to resolve the issues.  But I don't know exactly how to get to that point from the current workflow and limitations around community vs. product artifacts.

Can we have two separate BOMs, one for community and one for product, and require upgrades to be verified in both cases?  Or is there another way to prevent issues that occur during the cutover from community to product artifacts?

**Comment by ge0ffrey** [comment]
+1 to split up community and product boms...
... This branch (master) is the community bom :)

**Comment by ge0ffrey** [comment]
Can we close this PR? It doesn't look this PR is going anywhere...

**Comment by wolfc** [comment]
Point me to the maintenance branch and I'll re-file. :smile:

**Comment by ge0ffrey** [comment]
@psiroky proposed to introduce release branches (see ip-dev mailing list discussion). I fully stand behind that proposal. A huge scope creep got added though so it got put on the backburner :(

**Comment by psiroky** [comment]
Unfortunately, the release branches will only solve some of the issues. I will look at them again though, as we will need to branch anyway once we start to align to newer EAP versions.

We currently don't have maintenance branch with product versions.

**Comment by mareknovotny** [comment]
This really old PR not needed anymore.

**Pull request closed without merging**
