### PR TITLE
Upgrade jgit to v4.4.1.201607150455-r

### PR DESCRIPTION
**Pull request by manstis**
This fixes an issue using jgit on Windows: https://www.eclipse.org/forums/index.php/t/1031740/

### CODE REVIEW

**Comment by hchiorean** [comment]
+1

**Comment by psiroky** [comment]
+1

**Comment by manstis** [comment]
@hchiorean @psiroky @mbiarnes Hi.. anything I need to do to "encourage" the merge of this?

**Comment by psiroky** [comment]
@manstis we need one more vote from @cunningt. Tom could you please take a look?

**Comment by etirelli** [comment]
@cunningt can you please take a look at this PR? this is blocking a number of tickets on BxMS:

https://issues.jboss.org/browse/RHBRMS-2525

https://issues.jboss.org/browse/DROOLS-964

https://issues.jboss.org/browse/RHBRMS-1382

**Comment by cunningt** [comment]
+1

**Comment by psiroky** [comment]
@etirelli I am afraid we can't backport this into 6.x branch, because jgit 4.x needs Java 7+ (see https://wiki.eclipse.org/JGit/New_and_Noteworthy/4.0#Update_to_Java_7) and we still need to support Java 6 for the 6 series.

**Comment by etirelli** [comment]
Thank you for the information @psiroky .

**Pull request merged**
