### PR TITLE
Upgrade JGit from 3.7.1.201504261725-r to 4.3.1.201605051710-r

### PR DESCRIPTION
**Pull request by psiroky**
* there are some API changes between the releases, most notably
   regarding Hooks. See https://wiki.eclipse.org/JGit/New_and_Noteworthy
   for more info

@porcelli, @ederign do you agree with this JGit upgrade? I briefly looked at the release notes and there are quite a few bug fixes and also some performance improvements, so I think it would be worth the effort. I also tried to run the UF build with the new version and after few minor fixes all the tests are passing.

### CODE REVIEW

**Comment by hchiorean** [comment]
ModeShape uses `3.7.1`. If the version change is important to you, then I guess +1 but I will override it locally for ModeShape.

**Comment by psiroky** [comment]
@hchiorean I had no idea ModeShape was using jgit. Are there any plans to upgrade?

I believe the change is not that important for us, so we can live without it.

**Comment by hchiorean** [comment]
there are no plans to upgrade, which is why I said that if you need the version change, I'm fine with overriding it locally.

**Comment by psiroky** [comment]
@hchiorean ok, thanks for clarification. @porcelli, @ederign WDYT should we upgrade?

**Comment by porcelli** [comment]
+1 to upgrade; I'd say this is almost a critical upgrade due the Git Ketch!

**Comment by cunningt** [comment]
+1

**Comment by psiroky** [comment]
Based on the above discussion, I will merge this upgrade and Horia will override the version locally for ModeShape.

**Pull request merged**
