### PR TITLE
Ban uberjar mockito-all

### PR DESCRIPTION
**Pull request by psiroky**

### CODE REVIEW

**Comment by objectiser** [comment]
+1

**Comment by hchiorean** [comment]
I'm not sure I agree with this: why are we banning a test jar ? i.e. mockito is most likely never used for anything else.
ModeShape uses both `mockito-all` and `junit` from CR30 and they work fine together.

**Comment by psiroky** [comment]
I agree that it is a lower priority as it is a test jar, but it still disrupts `<test>` classpath dependency management. We recently hit an incompatibility issue with `junit` and `hamcrest-core` which is directly bundled inside `mockito-all`. You can replace `mockito-all` with `mockito-core`.

**Comment by hchiorean** [comment]
ok, I do agree that bundling `hamcrest` is not good so +1

**Comment by psiroky** [comment]
Thansk @hchiorean!

**Comment by cunningt** [comment]
+1

**Pull request merged**
