### PR TITLE
Update hibernate search to 4.5.2.Final according to discussion in ip-dev

### PR DESCRIPTION
**Pull request by ryanzhang**
Reopen this from https://github.com/jboss-integration/jboss-integration-platform-bom/pull/170

### CODE REVIEW

**Comment by hchiorean** [comment]
+1

**Comment by objectiser** [comment]
+1

**Comment by ge0ffrey** [comment]
+1

**Comment by kcbabo** [comment]
+1

**Comment by ge0ffrey** [comment]
@ryanzhang Unfortunately this PR no longer automatically merges due to some of the other PR's that have been merged... Would you mind rebasing it to master (by simply rebasing it to master in your fork's branch (and solve the 1-line merge conflict), it doesn't need a new PR as the changes will be reflected in this PR once you push (you might need to force push to your remote repo (never force push to the blessed repo))).

**Comment by mbiarnes** [comment]
@ryanzhang can this PR e removed as in PR #182 it is proposed to upgrade hibernate search to 4.5.3.Final to align with EAP 6.4.0.CR1

**Comment by ryanzhang** [comment]
Thanks Michael! Closed.

**Pull request closed without merging**
