### PR TITLE
SWITCHYARD-2624 Upgrade integration-platform-bom to use Camel 2.15.x

### PR DESCRIPTION
**Pull request by igarashitm**
Upgrading camel version to 2.15.2. Also update com.sun.xml.bind from 2.2.5 to 2.2.11 to avoid JAXB related issue camel-2.15 hit.

### CODE REVIEW

**Comment by hchiorean** [comment]
+1

**Comment by psiroky** [comment]
@igarashitm just want to check why are you proposing to upgrade of Camel. Is this related to alignment to some container? Will it be used by the next Fuse release (6.2)?

**Comment by igarashitm** [comment]
@psiroky The camel version in Fuse 6.2 product branch is already 2.15. This is just catching up that on community branch.

**Comment by psiroky** [comment]
@igarashitm great, thanks for the info!

+1 in that case.

**Comment by objectiser** [comment]
+1

**Comment by cunningt** [comment]
+1

**Comment by psiroky** [comment]
Merged in as we have all the needed acks.

**Pull request merged**
