### PR TITLE
upgrade org.hibernate to align with EAP 6.4.3

### PR DESCRIPTION
**Pull request by mbiarnes**

### CODE REVIEW

**Comment by hchiorean** [comment]
+1

**Comment by psiroky** [comment]
+1

**Comment by objectiser** [comment]
+1

**Comment by mbiarnes** [comment]
Sorry about not waiting for last +1, but we needed to merge the PR to proceed with release. It is just a minor change to align with EAP 6.4.3  and we assumed the SY would be OK with them.

**Pull request merged**
