### PR TITLE
upgrade versions of maven-enforcer plugin extensions

### PR DESCRIPTION
**Pull request by mbiarnes**

### CODE REVIEW

**Comment by kiereleaseuser2** [comment]
Build finished.

**Comment by mareknovotny** [comment]
what is the reason to upgrade these dependencies for enforcer plugin?

**Comment by ge0ffrey** [comment]
@mareknovotny We should upgrade all our maven plugin versions (and such enforcer rule deps) to avoid JDK 11 build issues that have already been fixed in the latest and greatest version. Unless of course upgrading breaks our build.

Sooner or later we need to upgrade them anyway, and most of them are only compatible with OpenJDK 11 from a specific, recent version.

**Comment by jhrcek** [comment]
@ge0ffrey regarding upgrading maven plugins to (and keeping them updated), I can't agree more. We need to make sure that we're using consistent version of different plugins across our build (which is not the case at the moment).

With that in mind I included the answer to the question *Are we using consistent versions of plugins in our daily build?* into my [daily report](https://rhba-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/custom/job/jhrcek/job/ckbuild/lastSuccessfulBuild/artifact/report.html) - section *Plugins with multiple versions*. We should use that as a starting point to make plugin versions used throughout the build consistent.

Let me just share one related maven tip: maven can automatically display the available plugin updates if you specify minimal supported maven in the project's pom (by adding `<prerequisites<maven>3.5.4</maven></prerequisites>`) and then you run `mvn versions:display-plugin-updates` in that project, you get some useful info like this:

```
[INFO] --- versions-maven-plugin:2.2:display-plugin-updates (default-cli) @ dashbuilder-webapp ---
[INFO] 
[INFO] The following plugin updates are available:
[INFO]   maven-resources-plugin ................................. 2.6 -> 3.1.0
[INFO] 
[WARNING] The following plugins do not have their version specified:
[WARNING]   org.codehaus.mojo:gwt-maven-plugin ......................... 2.8.2
[INFO] 
[INFO] Project inherits minimum Maven version as: 3.5.4
[INFO] Plugins require minimum Maven version of: 3
```

**Comment by mareknovotny** [comment]
@ge0ffrey so these 2 upgrades are required for java 11 if I understand correctly, right?

I agree with @jhrcek about versions of plugins should be consistent and only with the reason to differ.

the only concern right now is the proposed change time plan due some deadlines ;)

**Comment by jhrcek** [comment]
@mareknovotny sure thing. My comment was only concerning long term Ideal that we should strive for, not blocking this PR.

**Comment by mareknovotny** [comment]
I think we can merge it, I was just curious for real reason not just the latest is the greates ;)

**Pull request merged**
