### PR TITLE
upgraded to a EAP 6 compatible version

### PR DESCRIPTION
**Pull request by mbiarnes**
alignment to EAP 6.4.0.CR1
the version 4.5.3.Final is not compatible with EAP 6 so we have to go back to 4.4.6.Final

### CODE REVIEW

**Comment by hchiorean** [comment]
-1
As discussed previously on the IP mailing list, EAP 6.4 will come out with 4.6.0.Final-redhat-x. Since this is not available in the community, we need a community equivalent which is API compatible.
According to Sanne (see previously mentioned thread) this should be either `4.5.3` or `4.5.2`.

**Comment by etirelli** [comment]
Hiram, that is not correct. Quoting:

Edson: 
"Sanne, from your e-mail, is my understanding correct that hibernate-search 4.4.x is compatible with EAP 6, 4.5.x is *not* compatible, and 4.6.x is compatible again?"

Sanne: 
"yes exactly. I realise it's confusing, let me explain why - I hope it helps.

Essentially we have frozen branch 4.4 for long term maintenance and products (years ago), and moved on to 4.5 to support WildFly and future. Then Infinispan required a lot of improvements over the last few years, and these naturally happened in 4.5. Then JDG was productized out of Infinispan, and so it went with version 4.5 for the product.
We realized that was a mistake, so we backported all the patches which Infinispan and JDG would need back to 4.4.x as well and created version 4.4.7.Final, and asked the JDG team to get back to use 4.4.7.Final as well to align with all product versions.

But for JDG and customers it wasn't possible to change a depedendency version "downwards" 4.5 -> 4.4.7 as that would look strange to end users, so we "renamed" the version 4.4.7 to 4.6.0.

So now we have to deal with this confusion, and I have to send such explanations often  but at least we don't have to send explanations about a downgrade to customers."

**Comment by mbiarnes** [comment]
@hchiorean 
See Edsons comment:
"4.5.x is not compatible" with EAP 6 
So I think 4.5.x is not the right version. That's why I downgraded 4.5.3.Final to 4.4.6.Final.

**Comment by hchiorean** [comment]
This the email that I'm referring to - Sannes reply on the IP discussion:
>there is no community release for this branch.
Assuming you're *not* depending on the maven module hibernate-search-orm, you'll be good API-wise with community release 4.5.2.Final
The recap what we did, branch 4.6 takes:
 - the code from branch 4.5_latest for all modules except hibernate-search-orm
 - the code from branch 4.4_latest for module hibernate-search-orm
So essentially it's an identical copy of community release 4.5.2.Final but being compatible with JPA 2.0 (as in EAP) rather than the community build which is JPA 2.1 (as in WildFly).
Another good consequence is that it's also the same as used by JDG.

This is the BZ tracking the Hibernate Search version in EAP 6.4: https://bugzilla.redhat.com/show_bug.cgi?id=1188293

**Comment by hchiorean** [comment]
To clarify, I'm referring to the `hibernate-search-engine` artifact.

**Comment by etirelli** [comment]
Hiram, I forwarded you the e-mail from Sanne. We (Drools/jBPM) are ok either way, but Sanne is telling us that 4.5 will not work on EAP 6.x, and the IP BOM has to align as closely as possible to EAP 6.x. That's why we are going back to version 4.4.6 that was recommended by Sanne.

**Comment by hchiorean** [comment]
@etirelli: my name is Horia

I've asked Sanne to clarify on the IP mailing list.

**Comment by etirelli** [comment]
@hchiorean Sorry Horia, I confused your nickname with Hiram's. Apologies...

**Comment by Sanne** [comment]
So to iterate, among version of Hibernate Search:
 - 4.4.x is compatible with EAP6
 - 4.5.x is NOT compatible with EAP6 -> was meant for WildFly (JavaEE and JPA 2.1)
 - 4.6.x IS compatible with EAP6

EAP 6.4 contains '4.6.0.Final-redhat-2'

The latest community release of 4.4.x was 4.4.6. After that you could consider as '4.6.0'=='4.4.7'.

The version was artificially bumped, but '4.6.x' is API wise very similar to '4.4.x'.

It's correct to use 4.4.6 in community, if you're looking for the closest match of what's in EAP 6.4

**Comment by mbiarnes** [comment]
@Sanne:
thanks for clearing this up.

**Comment by hchiorean** [comment]
+1, in light of Sanne's latest comment

**Comment by objectiser** [comment]
+1

**Comment by kcbabo** [comment]
+1

**Comment by ge0ffrey** [comment]
+1

**Pull request merged**
