### PR TITLE
upgraded com.allen-sauer.gwt.dnd to align with kie-parent

### PR DESCRIPTION
**Pull request by mbiarnes**
upgraded com.allen-sauer.gwt.dnd

### CODE REVIEW

**Comment by manstis** [comment]
Note, this version of ```com.allen-sauer.gwt.dnd``` is needed for GWT2.7. See https://github.com/jboss-integration/jboss-integration-platform-bom/pull/193

**Comment by psiroky** [comment]
+1

**Comment by hchiorean** [comment]
+1

**Comment by objectiser** [comment]
+1

**Comment by mbiarnes** [comment]
I will close this PR, as merging https://github.com/jboss-integration/jboss-integration-platform-bom/pull/193 is not possible because this will break ModeShape Web Explorer application which uses GWT 2.5.1.
https://github.com/jboss-integration/jboss-integration-platform-bom/pull/192 and
https://github.com/jboss-integration/jboss-integration-platform-bom/pull/193 needs each other - so the best is to close this PR

**Pull request closed without merging**
