### PR TITLE
upgrade resteasy from 2.3.7.Final to 2.3.10.Final

### PR DESCRIPTION
**Pull request by mbiarnes**
alignment to EAP 6.4:
In EAP 6.4 it is used resteasy 2.3.10.Final-redhat-1.

### CODE REVIEW

**Comment by hchiorean** [comment]
-1, I can't find this version in Nexus.

**Comment by mbiarnes** [comment]
@hchiorean 
for example: https://origin-repository.jboss.org/nexus/content/groups/public-jboss/org/jboss/resteasy/resteasy-guice/2.3.10.Final/ ???

**Comment by ge0ffrey** [comment]
I see 2.3.10.Final on nexus now, it's 8 days old:
https://repository.jboss.org/nexus/index.html#nexus-search;gav~org.jboss.resteasy~resteasy-guice~~~~kw,versionexpand

**Comment by hchiorean** [comment]
+1 (my bad, it's there)

**Comment by objectiser** [comment]
+1

**Comment by psiroky** [comment]
It seems we are missing one more +1 (from SwitchYard?) @cunningt @kcbabo

**Comment by cunningt** [comment]
+1

**Pull request merged**
