### PR TITLE
upgrade org.apache.cxf to align with EAP 6.4.4

### PR DESCRIPTION
**Pull request by mbiarnes**

### CODE REVIEW

**Comment by psiroky** [comment]
+1

**Comment by objectiser** [comment]
+1

**Comment by cunningt** [comment]
+1

**Comment by psiroky** [comment]
Oops, I overlooked that @hchiorean did not yet replied. Sorry about that! Please let me know in case you would not agree with this change.

**Comment by hchiorean** [comment]
+1

**Pull request merged**
