### PR TITLE
BZ-1309248 Add keycloak into jboss-integration-bom

### PR DESCRIPTION
**Pull request by ryanzhang**
The same PR have been merged to origin/6.0.x as https://github.com/jboss-integration/jboss-integration-platform-bom/pull/266
So this should also be merged to master as well.

### CODE REVIEW

**Comment by psiroky** [comment]
+1

**Comment by ryanzhang** [comment]
@psiroky  Could you please merge this directly to master since this is the same as #266 which has been acked by all teams?

**Comment by psiroky** [comment]
@ryanzhang well, I could but since we won't release from master for some time anyway, it probably does not matter that much. I believe we should ack the changes on all banches. I'll wait few more days for the acks, if they don't arrive, I will merge.

**Comment by ryanzhang** [comment]
It's true. It's not really matter if it will be merged at the end.
Thanks!

**Comment by psiroky** [comment]
Same change applied to 6.0.x, so merging here as well.

**Pull request merged**
