### PR TITLE
downgraded picketbox to align with JBEAP 7.0.0.ER7

### PR DESCRIPTION
**Pull request by mbiarnes**

### CODE REVIEW

**Comment by hchiorean** [comment]
+1

**Comment by psiroky** [comment]
+1

**Comment by cunningt** [comment]
+1

**Comment by psiroky** [comment]
Looking again at the EAP 7 deps, it seems we should be actually using 4.9.6.Final. @mbiarnes could you please double check this?

**Comment by mbiarnes** [comment]
@psiroky yepp - you're right. 
During the constant upgrades of the ERs there was a upgrade from 4.9.2 --> 4.9.6.
Now JBEAP uses org.picketbox:authorization-spi:4.9.6.Final-redhat-1 - so we should instead upgrade
to 4.6.9 too.
Please close this PR.

**Pull request closed without merging**
