### PR TITLE
[AF-1555]: Upgrade to Wildfly14

### PR DESCRIPTION
**Pull request by adrielparedes**
## Description

Upgrade from Wildfly 11 to 14

@mbiarnes please could you check this PR? Also I sent you an email of my concerns about SNAPSHOT version.

## Related to:
* https://github.com/jboss-integration/jboss-integration-platform-bom/pull/427
* https://github.com/errai/errai/pull/363
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/843
* https://github.com/kiegroup/appformer/pull/483
* https://github.com/kiegroup/kie-wb-common/pull/2147
* https://github.com/kiegroup/jbpm/pull/1336
* https://github.com/kiegroup/jbpm-wb/pull/1206
* https://github.com/kiegroup/drools/pull/2086
* https://github.com/kiegroup/droolsjbpm-integration/pull/1583
* https://github.com/kiegroup/kie-wb-distributions/pull/821 
* https://github.com/kiegroup/kie-docs/pull/1108
* https://github.com/kiegroup/optaplanner/pull/437
* https://github.com/kiegroup/optaplanner-wb/pull/304

### CODE REVIEW

**Comment by kiereleaseuser2** [comment]
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

**Comment by mbiarnes** [comment]
@adrielparedes 
Hi - please close this PR since the upgrade of com.fasterxml.jackson to 2.9.5 is in jboss-ip-bom 8.2.0.Final: https://github.com/jboss-integration/jboss-integration-platform-bom/blob/8.2.0.Final/pom.xml#L126 - so once the kie-reps are updated to use this jboss-ip-bom the version will be automatically there

**Comment by adrielparedes** [comment]
@mbiarnes Thanks! Closing and waiting for 8.2.0.Final

**Comment by adrielparedes** [comment]
Reopening and targeting for 8.2.1.Final

**Comment by kiereleaseuser2** [comment]
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

**Pull request closed without merging**
