### PR TITLE
JBPM-7812 - Upgrade MySQL driver to version 5.1.47

### PR DESCRIPTION
**Pull request by cristianonicolai**

### CODE REVIEW

**Comment by cristianonicolai** [comment]
@mswiderski fyi

**Comment by kiereleaseuser2** [comment]
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

**Comment by cristianonicolai** [comment]
@mbiarnes can you take a look on this, thanks.

**Comment by mbiarnes** [comment]
@cristianonicolai this needs a change also in droolsjbpm-build-bootstrap since this version can be moved to jboss-ip-bom. I am doing a test - tomorrow I can say if it worked.

**Comment by mbiarnes** [comment]
@cristianonicolai @mswiderski 
Why this version? 
The version aligned to EAP 7.1. is http://www.qa.jboss.com/jdbc-drivers-products/EAP/7.1.0/mysql57/jdbc4/ 
mysql-connector-java 8.0.12
We should align to EAP 7.1.4?

**Comment by mswiderski** [comment]
this was the latest version from 5.1 and since we were at that level staying at 5.1.x was the safe choice. Moreover, it was confirmed to work well by some community users.

**Pull request merged**
