### PR TITLE
[RHBRMS-2673] upgraded tika to prevent XML External Entity vulnerability

### PR DESCRIPTION
**Pull request by mbiarnes**

### CODE REVIEW

**Comment by hchiorean** [comment]
+1

**Comment by hchiorean** [comment]
note that this upgrade is not enough, because this BOM contains older versions of Tika transitive dependencies which also require an upgrade for Tika `1.14` to work properly:
```
<version.org.apache.commons.compress>1.12</version.org.apache.commons.compress>
<version.commons-io>2.5</version.commons-io>
<version.org.apache.poi>3.15</version.org.apache.poi>
```

**Comment by psiroky** [comment]
+1 to upgrade the other deps as well

**Comment by mbiarnes** [comment]
@psiroky transitive dependencies for tika upgraded

**Pull request merged**
