### PR TITLE
Add picketlink 2.5.4.SP7 deps

### PR DESCRIPTION
**Pull request by psiroky**

### CODE REVIEW

**Comment by hchiorean** [comment]
the picketlink version I see in EAP 6.4.4 is `2.5.4.SP7-redhat-1`, with `2.5.4.SP7` being available in Nexus. Shouldn't that version be used ?

**Comment by psiroky** [comment]
You are right @hchiorean. I updated the PR. Thanks for catching this!

**Comment by hchiorean** [comment]
+1

**Comment by cunningt** [comment]
+1

**Pull request merged**
