### PR TITLE
upgraded version.com.google.gwt to align with kie-platform.bom

### PR DESCRIPTION
**Pull request by mbiarnes**

### CODE REVIEW

**Comment by manstis** [comment]
Note, if we move to GWT2.7 we need the version of ```com.allen-sauer.gwt.dnd``` updated too. See https://github.com/jboss-integration/jboss-integration-platform-bom/pull/192

**Comment by psiroky** [comment]
+1

**Comment by hchiorean** [comment]
-1
This [breaks](https://gist.github.com/hchiorean/6ae22aa2fd0c72c4d6ad) ModeShape Web Explorer application which uses GWT 2.5.1.
See link for compilation failure.

**Comment by psiroky** [comment]
@hchiorean are there any plans for ModeShape to move to GWT 2.7.0?

**Comment by hchiorean** [comment]
not right now. 
I don't know what 2.7.0 brings in compared to 2.5.1, but our current application works fine with 2.5.1. I also don't know why 2.7.0 is not backwards compatible....

**Comment by mbiarnes** [comment]
I will close this PR, it is not possible to upgrade GWT because this will break ModeShape Web Explorer application which uses GWT 2.5.1.
#193 and
#192 needs each other - so the best is to close this PR

**Pull request closed without merging**
